// LE Secure Connections crypto (Core Spec Vol 3, Part H, 2.2.5–2.2.9).
//
// SCOPE: the SMP cryptographic toolbox the pairing handshake needs:
// P-256 ECDH shared secret (ble_gap_lesc_p256_pk_t / ble_gap_lesc_dhkey_t
// shapes: {X,Y} and DHKey both little-endian on the wire), AES-CMAC
// (the single block primitive every function below builds on), and the
// f4 confirm / f5 key-generation / f6 check / g2 numeric-compare
// functions. Endianness follows the bumble reference exactly
// (bumble/crypto/__init__.py, itself a line-for-line port of the spec
// text): public test vectors below were generated BY bumble on this
// host, so any byte-order drift fails loudly here, not on air.
//
// Wire rule (S132 ble_gap.h + Core Spec v4.2 Vol 3 Part H 2.3.5.6):
// the SMP protocol format carries P-256 points and DHKeys
// LITTLE-endian; the primitives take BIG-endian (mathematical) order
// internally and reverse at the boundary — see `le_to_be`.
// f4/f5/f6/g2 take their inputs in PROTOCOL (LE) order and reverse
// internally, exactly like bumble's f4/f5/f6/g2.

use cmac::{Cmac, Mac};
use p256::{PublicKey, SecretKey};
use p256::elliptic_curve::sec1::ToSec1Point;

/// Reverse endianness (protocol LE <-> math BE).
fn rev(b: &[u8]) -> Vec<u8> {
    b.iter().rev().cloned().collect()
}

/// AES-128 single block encrypt (raw primitive, no swapping).
/// Test-only: the FIPS-197 sanity vector calls it; production paths
/// all go through [`aes_cmac_be`].
#[cfg(test)]
fn aes128_block(key_be: &[u8], blk_be: &[u8]) -> [u8; 16] {
    use aes::Aes128;
    use cipher::{Block, BlockCipherEncrypt, Key, KeyInit};
    let key_arr = Key::<Aes128>::try_from(key_be).expect("key len");
    let cipher = Aes128::new(&key_arr);
    let mut b: Block<Aes128> = Block::<Aes128>::try_from(blk_be).expect("block len");
    cipher.encrypt_block(&mut b);
    let mut out = [0u8; 16];
    out.copy_from_slice(b.as_slice());
    out
}

/// AES-CMAC, big-endian in/out (bumble's `aes_cmac`: cryptography lib
/// CMAC over AES(k), big-endian both sides). A 256-bit key selects
/// AES-256, a 128-bit key AES-128 — bumble passes both (DHKey-derived
/// T inputs are 128-bit; the f6 cross-check key happens to be 256-bit).
pub fn aes_cmac_be(msg: &[u8], key_be: &[u8]) -> [u8; 16] {
    use aes::{Aes128, Aes256};
    use cipher::KeyInit;
    // Big-endian out from the low-level primitive (avoids repeating
    // the finalize/copy dance per key size).
    fn final_be<M: Mac>(mac: M) -> [u8; 16] {
        let out = mac.finalize().into_bytes();
        let mut r = [0u8; 16];
        r.copy_from_slice(out.as_slice());
        r
    }
    match key_be.len() {
        16 => {
            let mut mac =
                <Cmac<Aes128> as KeyInit>::new_from_slice(key_be).expect("cmac key len");
            Mac::update(&mut mac, msg);
            final_be(mac)
        }
        32 => {
            let mut mac =
                <Cmac<Aes256> as KeyInit>::new_from_slice(key_be).expect("cmac key len");
            Mac::update(&mut mac, msg);
            final_be(mac)
        }
        n => panic!("cmac key len: {n}"),
    }
}

/// f4(U, V, X, Z): LE Secure Connections confirm-value generation
/// (Core Spec 2.2.6). U,V = peer/local public X coords (LE 32B each),
/// X = random (LE 16B), Z = 0x00 (1B). Returns confirm (LE 16B).
/// Bumble: reverse(aes_cmac(reverse(U)+reverse(V)+Z, reverse(X))).
pub fn smp_f4(u_le: &[u8], v_le: &[u8], x_le: &[u8], z: u8) -> [u8; 16] {
    let mut m = Vec::with_capacity(65);
    m.extend_from_slice(&rev(u_le));
    m.extend_from_slice(&rev(v_le));
    m.push(z);
    let t = aes_cmac_be(&m, &rev(x_le));
    let mut out = [0u8; 16];
    for (i, b) in t.iter().rev().enumerate() {
        out[i] = *b;
    }
    out
}

/// f5(W, N1, N2, A1, A2): LE Secure Connections key generation
/// (Core Spec 2.2.7). W = DHKey (LE 32B), N1/N2 = nonces (LE 16B),
/// A1/A2 = addr+type (LE 7B each). Returns (MacKey, LTK), both LE 16B.
/// Bumble: salt 6C888391AAF5A53860370BDB5A6083BE; T = cmac_BE(rev(W),
/// salt); MacKey = rev(cmac_BE(0x00||'btle'||rev(N1)..||rev(A2)||0100,
/// T)); LTK = same with leading 0x01.
pub fn smp_f5(
    w_le: &[u8],
    n1_le: &[u8],
    n2_le: &[u8],
    a1_le: &[u8],
    a2_le: &[u8],
) -> ([u8; 16], [u8; 16]) {
    let salt = [
        0x6Cu8, 0x88, 0x83, 0x91, 0xAA, 0xF5, 0xA5, 0x38, 0x60, 0x37, 0x0B, 0xDB, 0x5A, 0x60,
        0x83, 0xBE,
    ];
    let t = aes_cmac_be(&rev(w_le), &salt);
    let key_id = [0x62u8, 0x74, 0x6C, 0x65]; // 'btle'
    let mut mk_in = Vec::with_capacity(53);
    mk_in.push(0x00);
    mk_in.extend_from_slice(&key_id);
    mk_in.extend_from_slice(&rev(n1_le));
    mk_in.extend_from_slice(&rev(n2_le));
    mk_in.extend_from_slice(&rev(a1_le));
    mk_in.extend_from_slice(&rev(a2_le));
    mk_in.extend_from_slice(&[0x01, 0x00]);
    let mk_be = aes_cmac_be(&mk_in, &t);
    let mut lt_in = mk_in;
    lt_in[0] = 0x01;
    let lt_be = aes_cmac_be(&lt_in, &t);
    let mut mk = [0u8; 16];
    let mut lt = [0u8; 16];
    for (i, b) in mk_be.iter().rev().enumerate() {
        mk[i] = *b;
    }
    for (i, b) in lt_be.iter().rev().enumerate() {
        lt[i] = *b;
    }
    (mk, lt)
}

/// f6(W, N1, N2, R, IOcap, A1, A2): LE Secure Connections DHKey-check
/// generation (Core Spec 2.2.8). W = MacKey (LE 16B); N1/N2 (LE 16B);
/// R = r (LE 16B, passkey bytes or zeros); IOcap (3B); A1/A2 (LE 7B).
/// Returns check value (LE 16B).
/// Bumble: reverse(cmac_BE(rev(N1)+rev(N2)+rev(R)+rev(IO)+rev(A1)+
/// rev(A2), rev(W))).
pub fn smp_f6(
    w_le: &[u8],
    n1_le: &[u8],
    n2_le: &[u8],
    r_le: &[u8],
    iocap: &[u8],
    a1_le: &[u8],
    a2_le: &[u8],
) -> [u8; 16] {
    let mut m = Vec::with_capacity(80);
    m.extend_from_slice(&rev(n1_le));
    m.extend_from_slice(&rev(n2_le));
    m.extend_from_slice(&rev(r_le));
    m.extend_from_slice(&rev(iocap));
    m.extend_from_slice(&rev(a1_le));
    m.extend_from_slice(&rev(a2_le));
    let t = aes_cmac_be(&m, &rev(w_le));
    let mut out = [0u8; 16];
    for (i, b) in t.iter().rev().enumerate() {
        out[i] = *b;
    }
    out
}

/// g2(U, V, X, Y): LE Secure Connections numeric-comparison value
/// (Core Spec 2.2.9). U,V = public X coords (LE 32B), X = nonce
/// (LE 16B), Y = nonce (LE 16B). Returns u32; firmware shows % 1000000
/// (6 digits). Bumble: int.from_bytes(cmac_BE(rev(U)+rev(V)+rev(Y),
/// rev(X))[-4:], 'big').
pub fn smp_g2(u_le: &[u8], v_le: &[u8], x_le: &[u8], y_le: &[u8]) -> u32 {
    let mut m = Vec::with_capacity(80);
    m.extend_from_slice(&rev(u_le));
    m.extend_from_slice(&rev(v_le));
    m.extend_from_slice(&rev(y_le));
    let t = aes_cmac_be(&m, &rev(x_le));
    // NOTE: bumble slices the BIG-endian CMAC output's LAST 4 bytes
    // and reads them big-endian: t[12..16] of the BE tag.
    u32::from_be_bytes([t[12], t[13], t[14], t[15]])
}

/// P-256 ECDH shared secret (Core Spec 2.3.5.6 DHKey): scalar-mult of
/// our private scalar (BE 32B) by the peer's public point. The peer
/// point arrives in SMP protocol order: X (LE 32B) ++ Y (LE 32B);
/// the S132 keyset stores it the same way (ble_gap_lesc_p256_pk_t:
/// {X,Y} little-endian). Returns DHKey (LE 32B) or None when the
/// peer point is not on the curve (silicon would fail the procedure).
pub fn lesc_dhkey(own_priv_be: &[u8], peer_x_le: &[u8], peer_y_le: &[u8]) -> Option<[u8; 32]> {
    // Short/long coordinates are a malformed peer point, not a crash:
    // silicon fails the pairing procedure, so return None (the reply
    // arm maps this to INVALID_PARAM — see lesc_peer_key_valid).
    if peer_x_le.len() != 32 || peer_y_le.len() != 32 {
        return None;
    }
    let sk = SecretKey::from_slice(own_priv_be).ok()?;
    // Protocol LE -> SEC1 uncompressed BE: 0x04 || BE(X) || BE(Y).
    let mut sec1 = [0u8; 65];
    sec1[0] = 0x04;
    for (i, b) in peer_x_le.iter().rev().enumerate() {
        sec1[1 + i] = *b;
    }
    for (i, b) in peer_y_le.iter().rev().enumerate() {
        sec1[33 + i] = *b;
    }
    let pk = PublicKey::from_sec1_bytes(&sec1).ok()?;
    let shared = sk.diffie_hellman(&pk);
    let be = shared.raw_secret_bytes();
    let mut le = [0u8; 32];
    for (i, b) in be.iter().rev().enumerate() {
        le[i] = *b;
    }
    Some(le)
}

/// Our P-256 public key from our private scalar (BE 32B) in SMP
/// protocol order: X (LE 32B) ++ Y (LE 32B) — the exact 64 bytes the
/// LESC_DHKEY_REQUEST peer key / OOB pk fields carry. None on bad
/// scalar (zero / >= n — never for RNG-fed scalars, loud here).
pub fn lesc_public_key(own_priv_be: &[u8]) -> Option<[u8; 64]> {
    let sk = SecretKey::from_slice(own_priv_be).ok()?;
    let enc = PublicKey::from(&sk).to_sec1_point(false);
    let x = enc.x()?;
    let y = enc.y()?;
    let mut out = [0u8; 64];
    for (i, b) in x.iter().rev().enumerate() {
        out[i] = *b;
    }
    for (i, b) in y.iter().rev().enumerate() {
        out[32 + i] = *b;
    }
    Some(out)
}

/// Validate a peer P-256 public key (SMP order X_LE ++ Y_LE) is on the
/// curve. The LESC_DHKEY_REPLY arm uses this: a garbage peer point
/// refuses INVALID_PARAM like silicon (which fails the procedure),
/// instead of faulting the host ECDH backend.
pub fn lesc_peer_key_valid(x_le: &[u8], y_le: &[u8]) -> bool {
    if x_le.len() != 32 || y_le.len() != 32 {
        return false;
    }
    let mut sec1 = [0u8; 65];
    sec1[0] = 0x04;
    for (i, b) in x_le.iter().rev().enumerate() {
        sec1[1 + i] = *b;
    }
    for (i, b) in y_le.iter().rev().enumerate() {
        sec1[33 + i] = *b;
    }
    // Reject the point at infinity encoding (all-zero) explicitly:
    // some backends accept it, silicon never does.
    if sec1[1..].iter().all(|&b| b == 0) {
        return false;
    }
    PublicKey::from_sec1_bytes(&sec1).is_ok()
}

/// AffinePoint import (test-only helper): BE X ++ BE Y -> point.
#[cfg(test)]
pub(crate) fn affine_be(
    x_be: &[u8],
    y_be: &[u8],
) -> Option<p256::AffinePoint> {
    use p256::elliptic_curve::sec1::FromSec1Point;
    let mut sec1 = [0u8; 65];
    sec1[0] = 0x04;
    sec1[1..33].copy_from_slice(x_be);
    sec1[33..65].copy_from_slice(y_be);
    p256::AffinePoint::from_sec1_bytes(&sec1).ok().into()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hx(s: &str) -> Vec<u8> {
        (0..s.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
            .collect()
    }

    #[test]
    fn aes_cmac_rfc4493_vectors() {
        // RFC 4493 (AES-CMAC, big-endian in/out — the ground truth
        // under bumble's aes_cmac, verified green on this host).
        let k = hx("2B7E151628AED2A6ABF7158809CF4F3C");
        assert_eq!(
            aes_cmac_be(&[], &k),
            hx("BB1D6929E95937287FA37D129B756746")[..],
            "cmac empty"
        );
        assert_eq!(
            aes_cmac_be(&hx("6BC1BEE22E409F96E93D7E117393172A"), &k),
            hx("070A16B46B4D4144F79BDD9DD04A287C")[..],
            "cmac 16B"
        );
        // Raw AES block sanity (FIPS-197): AES(K, 6BC1..) = 3AD77BB4...97.
        assert_eq!(
            aes128_block(&k, &hx("6BC1BEE22E409F96E93D7E117393172A")),
            hx("3AD77BB40D7A3660A89ECAF32466EF97")[..],
            "fips-197 block"
        );
    }

    #[test]
    fn smp_f4_cross_check() {
        // Frozen on this host FROM bumble (bumble/crypto f4, same inputs
        // the Rust test feeds): any byte-order drift fails here.
        let u = hx("5CEF2D5BC212C678E948F0B4609E3CA3");
        let v = hx("A6E8E7CC25A75F6E871290F3E5FFECB3");
        let x = hx("BDA278DAF090F402814A6310C8326C38");
        assert_eq!(smp_f4(&u, &v, &x, 0x00).to_vec(), hx("2fa1ea545933122d79a49e9a1427cd3d"));
    }

    #[test]
    fn smp_f5_f6_g2_cross_check() {
        // Frozen FROM bumble f5/f6/g2 on this host (fixed LE inputs;
        // expected outputs recorded from the reference run). Inputs are
        // SMP protocol order (LE); the implementation reverses
        // internally exactly like bumble.
        let u = hx("5CEF2D5BC212C678E948F0B4609E3CA3");
        let v = hx("A6E8E7CC25A75F6E871290F3E5FFECB3");
        let x = hx("BDA278DAF090F402814A6310C8326C38");
        let w = hx("BDA278DAF090F402814A6310C8326C38BDA278DAF090F402814A6310C8326C38");
        let n1 = hx("D5A38D943D33CDB551E1427D97A42760");
        let n2 = v.clone();
        let a1 = hx("11223344556601");
        let a2 = hx("AABBCCDDEEFF02");
        let (mk, ltk) = smp_f5(&w, &n1, &n2, &a1, &a2);
        assert_eq!(mk.to_vec(), hx("5d92ced8c7706f8f2237fc20012b848f"), "f5 mackey");
        assert_eq!(ltk.to_vec(), hx("914fd7c0f04e2ba824547322fb528c25"), "f5 ltk");
        let r = hx("00112233445566778899AABBCCDDEEFF");
        let io = hx("030201");
        assert_eq!(smp_f6(&w, &n1, &n2, &r, &io, &a1, &a2).to_vec(), hx("2fa701828e00cb772593fd706454b3b0"), "f6");
        let y = n1.clone();
        assert_eq!(format!("{:08x}", smp_g2(&u, &v, &x, &y)), "38e482e5", "g2");
    }

    #[test]
    fn lesc_ecdh_cross_check() {
        // Frozen FROM bumble EccKey on this host: two fresh keypairs,
        // shared secret symmetric both ways (BE math order). The Rust
        // entry takes our BE scalar + peer LE point and returns LE —
        // convert here and compare against the frozen BE secret.
        let a_priv_be = hx("60c4b55b4deb274dba4ea7d32e0747239d9fe0ea6af5432e3c8ec96733068731");
        let b_pubx_be = hx("a7d3f335843c4678274ea13b9fe174cbd1b970086e7c171d45b3c104805aef8f");
        let b_puby_be = hx("65e4862a2eeb7d0a58c0a51e1799a338a60e414ae8727416f4a0e4d093caa4c0");
        let b_pubx_le: Vec<u8> = b_pubx_be.iter().rev().cloned().collect();
        let b_puby_le: Vec<u8> = b_puby_be.iter().rev().cloned().collect();
        let shared_be = hx("c1bad8e98522c95886630260fe0210989066abadcb0ce46f5c1ab4fe59d7dbb9");
        let shared_le: Vec<u8> = shared_be.iter().rev().cloned().collect();
        assert_eq!(
            lesc_dhkey(&a_priv_be, &b_pubx_le, &b_puby_le).expect("ecdh"),
            shared_le[..],
            "ecdh shared secret"
        );
        // Public key derivation cross-check (SMP LE order).
        let a_pubx_be = hx("4a8724e3bd93818844ef105250d3c5d2528f780dd421f1765430dffe90117c4b");
        let a_puby_be = hx("570f17ca6028a3bb37e7e6302924f81467cc50dc756d2097544aef1a6bb1acbc");
        let mut pk_le = [0u8; 64];
        for (i, b) in a_pubx_be.iter().rev().enumerate() {
            pk_le[i] = *b;
        }
        for (i, b) in a_puby_be.iter().rev().enumerate() {
            pk_le[32 + i] = *b;
        }
        assert_eq!(lesc_public_key(&a_priv_be).expect("pubkey"), pk_le, "pubkey LE");
        assert!(lesc_peer_key_valid(&b_pubx_le, &b_puby_le), "peer valid");
        assert!(!lesc_peer_key_valid(&[0u8; 32], &[0u8; 32]), "infinity rejected");
        assert!(!lesc_peer_key_valid(&[1u8; 31], &[2u8; 32]), "short x rejected");
    }
}
